allowBuilds:
  esbuild: true
  '@sentry/cli': false
  core-js: false
  protobufjs: false
  sharp: false
  workerd: false
minimumReleaseAgeExclude:
  - '@sveltejs/adapter-cloudflare@8.0.0'
  - '@sveltejs/kit@3.0.0'
